-- Lo-Fi Study Space database schema (PostgreSQL 13+)
-- Runs automatically on server start. Every statement is idempotent.

CREATE TABLE IF NOT EXISTS users (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username      VARCHAR(20)  NOT NULL,
  email         VARCHAR(254) NOT NULL,
  password_hash TEXT         NOT NULL,
  display_name  VARCHAR(40)  NOT NULL,
  avatar        SMALLINT     NOT NULL DEFAULT 3 CHECK (avatar BETWEEN 0 AND 15),
  fav_subject   VARCHAR(60)  NOT NULL DEFAULT 'General',
  settings      JSONB        NOT NULL DEFAULT '{}'::jsonb,
  whiteboard    TEXT,                                   -- PNG data URL of the saved board
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);
-- case-insensitive uniqueness for login names
CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower ON users (lower(username));
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower    ON users (lower(email));

CREATE TABLE IF NOT EXISTS tasks (
  id           VARCHAR(40) PRIMARY KEY,                -- generated by the client (UUID)
  user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title        VARCHAR(200) NOT NULL,
  priority     VARCHAR(6)  NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high')),
  status       VARCHAR(8)  NOT NULL DEFAULT 'backlog' CHECK (status IN ('backlog', 'progress', 'done')),
  deadline     DATE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS tasks_user ON tasks (user_id);

CREATE TABLE IF NOT EXISTS notes (
  id         VARCHAR(40) PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title      VARCHAR(200) NOT NULL DEFAULT '',
  subject    VARCHAR(60)  NOT NULL DEFAULT 'General',
  body       TEXT         NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS notes_user ON notes (user_id, updated_at DESC);

-- one row per completed focus block; analytics are computed from this table
CREATE TABLE IF NOT EXISTS study_sessions (
  id         VARCHAR(40) PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  day        DATE        NOT NULL,                     -- the user's local calendar day
  started_at TIMESTAMPTZ NOT NULL,
  minutes    SMALLINT    NOT NULL CHECK (minutes BETWEEN 1 AND 600),
  subject    VARCHAR(60) NOT NULL DEFAULT 'General'
);
CREATE INDEX IF NOT EXISTS sessions_user_day ON study_sessions (user_id, day);

-- a friendship starts as a pending request and becomes 'accepted'
CREATE TABLE IF NOT EXISTS friendships (
  requester_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  addressee_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status       VARCHAR(8)  NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (requester_id, addressee_id),
  CHECK (requester_id <> addressee_id)
);
CREATE INDEX IF NOT EXISTS friendships_addressee ON friendships (addressee_id);

-- Study Street rooms; a room closes when its last member leaves
CREATE TABLE IF NOT EXISTS study_rooms (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  host_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  subject    VARCHAR(60) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_at  TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS rooms_open ON study_rooms (created_at) WHERE closed_at IS NULL;

CREATE TABLE IF NOT EXISTS room_members (
  room_id   UUID NOT NULL REFERENCES study_rooms(id) ON DELETE CASCADE,
  user_id   UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (room_id, user_id)
);
-- a user can be in at most one room at a time
CREATE UNIQUE INDEX IF NOT EXISTS room_members_one_room ON room_members (user_id);

-- ---------- Chats ----------
-- one row per conversation: a named group, or a direct chat between two friends
CREATE TABLE IF NOT EXISTS chats (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       VARCHAR(60),                          -- NULL for direct chats
  is_direct  BOOLEAN NOT NULL DEFAULT false,
  direct_key TEXT UNIQUE,                          -- 'smallerUserId:largerUserId', stops duplicate direct chats
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (is_direct = (direct_key IS NOT NULL)),
  CHECK (is_direct OR name IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS chat_members (
  chat_id      UUID NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
  user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role         VARCHAR(6)  NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
  joined_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_read_at TIMESTAMPTZ NOT NULL DEFAULT now(),  -- messages after this are unread
  PRIMARY KEY (chat_id, user_id)
);
CREATE INDEX IF NOT EXISTS chat_members_user ON chat_members (user_id);

CREATE TABLE IF NOT EXISTS messages (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chat_id    UUID NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
  user_id    UUID REFERENCES users(id) ON DELETE SET NULL,   -- NULL for system messages or deleted users
  kind       VARCHAR(6) NOT NULL DEFAULT 'text' CHECK (kind IN ('text', 'image', 'system')),
  body       TEXT NOT NULL,                                  -- text, an image data URL, or a system note
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS messages_chat_time ON messages (chat_id, created_at DESC);
